---
molecule:
  test:
    # sequence of commands to run when performing `molecule test`
    sequence:
      - destroy
      - create
      - converge
      - verify
      - destroy

vagrant:
  raw_config_args:
    - "ssh.insert_key = false"

  platforms:
    - name: centos-7
      box: bento/centos-7

#init:
#    # default platform to populate when doing `molecule init`
#    platform:
#      name: trusty64
#      box: trusty64
#      box_url: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
#    # templates to use when creating files during `molecule init`
#    templates:
#      molecule: molecule.yml.j2
#      playbook: playbook.yml.j2
#      spec_helper: spec_helper.rb.j2
#      default_spec: default_spec.rb.j2

  providers:
    - name: vmware_fusion
      type: vmware_fusion

  instances:
    - name: etcd-01
      ansible_groups:
        - etcd
    #- name: etcd-02
    #  ansible_groups:
    #    - etcd
    #- name: etcd-03
    #  ansible_groups:
    #    - etcd
