---
- hosts: etcd
  pre_tasks:
#    - apt: update_cache=yes cache_valid_time=3600
  roles:
    - role: ansible-etcd
      etcd_interface: eth1
      discovery_url : "{{ lookup('env','ETCD_DISCOVERY_URL') }}"
      discovery_dns : "{{ lookup('env','ETCD_DISCOVERY_SRV') }}"
      discovery_type: "{{ lookup('env','ETCD_DISCOVERY_TYPE') }}"

  tasks:
    - yum: name=curl
    - gem: name=facter
