---
- name: install Flannel
  yum: name=flannel state=installed

- name: configure Flannel daemon
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld
  notify: restart Flannel daemon

- name: install python-pip
  yum: name=python-pip state=installed

- name: install python-requests
  pip: name=requests state=present

- name: install python-etcd
  pip: name=python-etcd state=present

- name: configure Flannel network
  etcd: host="{{ hostvars[groups[etcd_servers_group][0]]['ansible_' + etcd_client_interface]['ipv4']['address'] }}"
        port="{{ etcd_client_port }}"
        key="{{ flannel_etcd_path }}/config"
        value="{{ flannel_config | string }}"
        state=present

- name: start Flannel daemon
  service: name=flanneld state=started enabled=yes
