---
galaxy_info:
  author: Bryan Hunt/John Dewey
  description: Install and manage etcd - centos only, requires ansible 2.x
  company:
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
  categories:
  - system
dependencies: []
