---
- hosts: etcd
  become: yes
  become_user: root
  vars:
    etcd_interface: eth1
  roles:
    - etcd

- hosts: kube-masters
  become: yes
  become_user: root
  roles:
    - flannel
    - kube-master

- hosts: kube-nodes
  become: yes
  become_user: root
  vars:
    docker_insecure_registry:
      - 192.168.121.152:5000
  roles:
    - flannel
    - docker
    - kube-node
