---
- hosts: etcd
  become: yes
  become_user: root
  vars:
    etcd_interface: eth1
  roles:
    - etcd

- hosts: kube-masters
  become: yes
  become_user: root
  roles:
    - flannel
    - kube-master

- hosts: kube-nodes
  become: yes
  become_user: root
  roles:
    - flannel
    - docker
    - kube-node
