---
- name: install Kubernetes node
  yum: name=kubernetes-node state=present

- name: configure kubelet
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet
  notify:
    - restart kubelet

- name: common Kubernetes config
  template: src=config.j2 dest=/etc/kubernetes/config
  notify:
    - restart Kubernetes proxy

- name: start kubelet
  service: name=kubelet state=started enabled=yes

- name: start Kubernetes proxy
  service: name=kube-proxy state=started enabled=yes
